version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ais_tracking
      POSTGRES_USER: ais_user
      POSTGRES_PASSWORD: ais_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ais_user -d ais_tracking"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ais_user:ais_password@postgres:5432/ais_tracking
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: