services:
  - type: web
    name: ais-tracking-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ais-tracking-db
          property: connectionString
      - key: AIS_HOST
        value: 153.44.253.27
      - key: AIS_PORT
        value: 5631
      - key: PORT
        value: 3001
    healthCheckPath: /health
    disk:
      name: ais-tracking-disk
      mountPath: /app/logs
      sizeGB: 1

  - type: worker
    name: ais-data-processor
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node dist/workers/data-processor.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ais-tracking-db
          property: connectionString
      - key: AIS_HOST
        value: 153.44.253.27
      - key: AIS_PORT
        value: 5631

databases:
  - name: ais-tracking-db
    databaseName: ais_tracking
    user: ais_user
    plan: starter
    postgresMajorVersion: 15
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections