services:
  - type: web
    name: ais-tracking-app
    env: node
    plan: free
    buildCommand: npm ci && npx tsc
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: DEBUG
      - key: DATABASE_URL
        fromDatabase:
          name: ais-tracking-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: BARENTSWATCH_CLIENT_ID
        sync: false
      - key: BARENTSWATCH_CLIENT_SECRET
        sync: false
      - key: BARENTSWATCH_SCOPE
        value: ais
      - key: BARENTSWATCH_AUTH_URL
        value: https://id.barentswatch.no/connect/token
      - key: BARENTSWATCH_API_URL
        value: https://live.ais.barentswatch.no
    healthCheckPath: /api/health

databases:
  - name: ais-tracking-db
    databaseName: ais_tracking
    user: ais_user
    plan: free
    postgresMajorVersion: 15