services:
  - type: web
    name: ais-tracking-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ais-tracking-db
          property: connectionString
      - key: AIS_HOST
        value: 153.44.253.27
      - key: AIS_PORT
        value: 5631
      - key: PORT
        value: 10000
    healthCheckPath: /health

databases:
  - name: ais-tracking-db
    databaseName: ais_tracking
    user: ais_user
    plan: free
    postgresMajorVersion: 15